package com.lasarobotics.ftc.monkeyc;

import com.lasarobotics.ftc.monkeyc.instruction.Instruction;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.hardware.HardwareMap;

import java.nio.ByteBuffer;
import java.security.InvalidParameterException;
import java.util.ArrayList;

/**
 * The MonkeyDo library handles executing instructions generated by MonkeyDo.
 */
public class MonkeyDo {

    HardwareMap map;
    OpMode mode;
    ByteBuffer instruction;

    public MonkeyDo(HardwareMap map, OpMode mode)
    {
        this.map = map;
        this.mode = mode;
    }

    public void run(ArrayList<Instruction> instructions)
    {
        for(Instruction i : instructions)
            i.execute(map);
    }
}
