package com.lasarobotics.ftc.monkeyc;

/**
 * Created by Ehsan on 7/8/2015.
 */

import android.content.Context;

import com.lasarobotics.ftc.controller.Controller;
import com.lasarobotics.ftc.util.Timers;
import com.qualcomm.robotcore.robocol.Command;
import java.util.ArrayList;

/**
 * The MonkeyDo library handles executing commands generated by MonkeyC.
 */
public class MonkeyDo {

    ArrayList<MonkeyData> commands;
    public Timers t;
    public MonkeyDo(String filename,Context context)
    {
        commands = MonkeyUtil.readFile(filename,context);
        t = new Timers();
        t.startClock("global");
    }

    public MonkeyData getNextCommand()
    {
        for( int i = 0; i < commands.size();i++){
            if (i+1 == commands.size()){
                return null;
            }
            MonkeyData next = commands.get(i+1);
            MonkeyData current = commands.get(i);
            if (next.time >= t.getClockValue("global") &&  t.getClockValue("global") >= current.time){
                return current;
            }
        }
        return null;
    }
}